apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_URL
        
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: USER_NAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: USER_PWD


---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort
